# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('streetName', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=30)),
                ('postalCode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('logo', models.FileField(upload_to='')),
            ],
        ),
    ]
