# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='streetNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='unitNumber',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='waitTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
