# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20160711_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='unitNumber',
            field=models.CharField(max_length=10),
        ),
    ]
