# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20160711_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='waitTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
