# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20160711_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='unitNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
