# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_auto_20160711_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTime', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='waitTime',
        ),
        migrations.AddField(
            model_name='clinic',
            name='availableTimes',
            field=models.ManyToManyField(to='clinics.Time'),
        ),
    ]
