# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20160912_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='logo',
        ),
    ]
