# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20160912_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='availableTimes',
        ),
        migrations.AddField(
            model_name='clinic',
            name='availableTimes',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
